version: "3"

services:
  db:
    image: postgres:12.1
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgresql_data:
    driver: local
