name: CI
on: push

jobs:
  quality_check:
    name: Quality check
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Read Ruby version
        run: echo "::set-output name=RUBY_VERSION::$(cat .ruby-version)"
        id: rbenv

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "${{ steps.rbenv.outputs.RUBY_VERSION }}"

      - run: sudo apt-get -yqq install libpq-dev

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Rubocop
        run: bundle exec rubocop --config .rubocop.yml -P

      - name: Test
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bin/rails test
        env:
          TEST_DATABASE_URL: postgres://postgres@localhost:5432/iguazu-test
          RAILS_ENV: test
